ThAmCo.Events/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ThAmCo.Events.Data
{
    public class CustomersController : Controller
    {
        private readonly EventsDbContext _context;

        public CustomersController(EventsDbContext context)
        {
            _context = context;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Customers.ToListAsync());
        }

        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .Include(c => c.Bookings)
                .ThenInclude(c => c.Event)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }



            return View(customer);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Surname,FirstName,Email")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Surname,FirstName,Email")] Customer customer)
        {
            if (id != customer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customer = await _context.Customers.FindAsync(id);
            _context.Customers.Remove(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(int id)
        {
            return _context.Customers.Any(e => e.Id == id);
        }
    }
}

ThAmCo.Events/Controllers/GuestBookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThAmCo.Events.Data;

namespace ThAmCo.Events.Views
{
    public class GuestBookingsController : Controller
    {
        private readonly EventsDbContext _context;

        public GuestBookingsController(EventsDbContext context)
        {
            _context = context;
        }

        // GET: GuestBookings
        public async Task<IActionResult> Index(int id)
        {


            var eventsDbContext = _context.Guests
                .Include(g => g.Customer)
                .Include(g => g.Event)
               .Where(g => g.EventId == id);

            return View(await eventsDbContext.ToListAsync());
        }

        // GET: GuestBookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guestBooking = await _context.Guests
                .Include(g => g.Customer)
                .Include(g => g.Event)
                .FirstOrDefaultAsync(m => m.CustomerId == id);
            if (guestBooking == null)
            {
                return NotFound();
            }
        
            return View(guestBooking);
        }

        // GET: GuestBookings/Create
        public IActionResult Create([FromQuery]int? eventId)
        {
            if (eventId == null) {
                return BadRequest();
            }


            var allCust = _context.Customers.ToList();
            var CurGuest = _context.Guests
                .Where(g => g.EventId == eventId)
                .ToList();
            allCust.RemoveAll(ac => CurGuest.Any(cg => cg.CustomerId == ac.Id));



            ViewData["CustomerId"] = new SelectList(allCust, "Id", "Email");

            ViewData["EventId"] = new SelectList(_context.Events, "Id", "Title", eventId);
            var eventname = _context.Events.Find(eventId);
            if (eventname == null) {
                return BadRequest();
            }
            ViewData["EventN"] = eventname.Title;
            return View();
        }

        // POST: GuestBookings/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CustomerId,EventId,Attended")] GuestBooking guestBooking)
        {
            if (ModelState.IsValid)
                if (_context.Guests.Any(g => g.EventId == guestBooking.EventId && g.CustomerId == guestBooking.CustomerId))
                {
                    ModelState.AddModelError(String.Empty, "Customer Already Registered For Event");
                }
                else 
                    {
                _context.Add(guestBooking);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Events");
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Email", guestBooking.CustomerId);
            ViewData["EventId"] = new SelectList(_context.Events, "Id", "Title", guestBooking.EventId);
            var eventname = await _context.Events.FindAsync(guestBooking.EventId);
            if (eventname == null)
            {
                return BadRequest();
            }
            ViewData["EventN"] = eventname.Title;

            return View(guestBooking);
        }

       

        // GET: GuestBookings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guestBooking = await _context.Guests.FindAsync(id);
            if (guestBooking == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Email", guestBooking.CustomerId);
            ViewData["EventId"] = new SelectList(_context.Events, "Id", "Title", guestBooking.EventId);
            return View(guestBooking);
        }

        // POST: GuestBookings/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CustomerId,EventId,Attended")] GuestBooking guestBooking)
        {
            if (id != guestBooking.CustomerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(guestBooking);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GuestBookingExists(guestBooking.CustomerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Email", guestBooking.CustomerId);
            ViewData["EventId"] = new SelectList(_context.Events, "Id", "Title", guestBooking.EventId);
            return View(guestBooking);
        }

        // GET: GuestBookings/Delete/5
        public async Task<IActionResult> Delete(int? Eventid, int? Customerid)
        {
            if (Eventid == null || Customerid == null)
            {
                return NotFound();
            }

            var guestBooking = await _context.Guests
                .Include(g => g.Customer)
                .Include(g => g.Event)
                .FirstOrDefaultAsync(m => m.CustomerId == Customerid && m.EventId == Eventid);
            if (guestBooking == null)
            {
                return NotFound();
            }

            return View(guestBooking);
        }

        // POST: GuestBookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? Eventid, int? Customerid)
        {
            var guestBooking = await _context.Guests
         .Include(g => g.Customer)
         .Include(g => g.Event)
         .FirstOrDefaultAsync(m => m.CustomerId == Customerid && m.EventId == Eventid);


            _context.Guests.Remove(guestBooking);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GuestBookingExists(int id)
        {
            return _context.Guests.Any(e => e.CustomerId == id);
        }
    }
}

ThAmCo.Events/Controllers/StaffBookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThAmCo.Events.Data;

namespace ThAmCo.Events.Views
{
    public class StaffBookingsController : Controller
    {
        private readonly EventsDbContext _context;

        public StaffBookingsController(EventsDbContext context)
        {
            _context = context;
        }

        // GET: StaffBookings
        public async Task<IActionResult> Index(int id)
        {
            var eventsDbContext = _context.Staffed
                .Include(g => g.Staff)
                .Include(g => g.Event)
                .Where(g => g.EventId == id);
            return View(await eventsDbContext.ToListAsync());
        }

        // GET: StaffBookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var StaffBooking = await _context.Staffed
                .Include(g => g.Staff)
                .Include(g => g.Event)
                .FirstOrDefaultAsync(m => m.StaffId == id);
            if (StaffBooking == null)
            {
                return NotFound();
            }
        
            return View(StaffBooking);
        }

        // GET: StaffBookings/Create
        public IActionResult Create([FromQuery]int? eventId)
        {
            if (eventId == null) {
                return BadRequest();
            }


            var allStaff = _context.Staffs.ToList();
            var CurStaff = _context.Staffed
                .Where(g => g.EventId == eventId)
                .ToList();
            allStaff.RemoveAll(ac => CurStaff.Any(cg => cg.StaffId == ac.Id));



            ViewData["StaffId"] = new SelectList(allStaff, "Id", "Email");

            ViewData["EventId"] = new SelectList(_context.Events, "Id", "Title", eventId);
            var eventname = _context.Events.Find(eventId);
            if (eventname == null) {
                return BadRequest();
            }
            ViewData["EventN"] = eventname.Title;
            return View();
        }

        // POST: StaffBookings/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StaffId,EventId,Attended")] StaffBookings StaffBooking)
        {
            if (ModelState.IsValid)
                if (_context.Staffed.Any(g => g.EventId == StaffBooking.EventId && g.StaffId == StaffBooking.StaffId))
                {
                    ModelState.AddModelError(String.Empty, "Staff Already Registered For Event");
                }
                else 
                    {
                _context.Add(StaffBooking);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Events");
            }
            ViewData["StaffId"] = new SelectList(_context.Staffs, "Id", "Email", StaffBooking.StaffId);
            ViewData["EventId"] = new SelectList(_context.Events, "Id", "Title", StaffBooking.EventId);
            var eventname = await _context.Events.FindAsync(StaffBooking.EventId);
            if (eventname == null)
            {
                return BadRequest();
            }
            ViewData["EventN"] = eventname.Title;

            return View(StaffBooking);
        }












        // GET: StaffBookings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var StaffBooking = await _context.Staffed.FindAsync(id);
            if (StaffBooking == null)
            {
                return NotFound();
            }
            ViewData["StaffId"] = new SelectList(_context.Staffs, "Id", "Email", StaffBooking.StaffId);
            ViewData["EventId"] = new SelectList(_context.Events, "Id", "Title", StaffBooking.EventId);
            return View(StaffBooking);
        }

        // POST: StaffBookings/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StaffId,EventId,Attended")] StaffBookings StaffBooking)
        {
            if (id != StaffBooking.StaffId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(StaffBooking);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StaffBookingExists(StaffBooking.StaffId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["StaffId"] = new SelectList(_context.Staffs, "Id", "Email", StaffBooking.StaffId);
            ViewData["EventId"] = new SelectList(_context.Events, "Id", "Title", StaffBooking.EventId);
            return View(StaffBooking);
        }

        // GET: StaffBookings/Delete/5
        public async Task<IActionResult> Delete(int? Eventid, int? Staffid)
        {
            if (Eventid == null ||Staffid == null)
            {
                return NotFound();
            }

            var StaffBooking = await _context.Staffed
                .Include(g => g.Staff)
                .Include(g => g.Event)
                .FirstOrDefaultAsync(m => m.StaffId == Staffid && m.EventId == Eventid);
            if (StaffBooking == null)
            {
                return NotFound();
            }

            return View(StaffBooking);
        }

        // POST: StaffBookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? Eventid, int? Staffid)
        {

            var StaffBooking = await _context.Staffed
                .Include(g => g.Staff)
                .Include(g => g.Event)
                .FirstOrDefaultAsync(m => m.StaffId == Staffid && m.EventId == Eventid);

         
            _context.Staffed.Remove(StaffBooking);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StaffBookingExists(int id)
        {
            return _context.Staffed.Any(e => e.StaffId == id);
        }
    }
}

ThAmCo.Events/Views/Events/Create.cshtml
@model ThAmCo.Events.Data.Event

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeId" class="control-label"></label>
                <select asp-for="TypeId" class="form-control"> </select>   
                <span asp-validation-for="TypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">

        $(document).ready(function () {

            $.ajax({

                url: "http://localhost:23652/api/eventtypes",
                method: "GET",
                crossDomain: true,
                success: function (result) {
                 
                    var types = '';
                    for (var i = 0; i < result.length; i++) {
                    
          
                        types = types+ '<option value ="' + result[i].id + '">' + result[i].title + '</options>';
                    } $('#TypeId').html(types);
                },
                error: function (result) {
                    alert("AJEX Error");
                }

            });

        });

    </script>
}

ThAmCo.Events/Views/Events/CreateVenue.cshtml
@model ThAmCo.Events.Data.Event

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" disabled />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeId" class="control-label"></label>
                <input asp-for="TypeId" class="form-control" disabled> </input>
                <span asp-validation-for="TypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VenueCode" class="control-label"></label>
                <input asp-for="VenueCode" class="form-control" disabled>
                <span asp-validation-for="VenueCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ThAmCo.Events/Views/Events/Delete.cshtml
@model ThAmCo.Events.Data.Event

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TypeId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TypeId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ThAmCo.Events/Views/Events/Details.cshtml
@model ThAmCo.Events.Data.EventDetailsViewModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TypeId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TypeId)
        </dd>
    </dl>
</div>
<div>
    <h4>Guests</h4>
    @if(Model.Guests.Any())
    {
        <partial name="_CustomerList" for="Guests"/>
    }
    else { <p>No Guests Booked </p>}
</div>
<div>
    <h4>Staff</h4>
    @if (Model.Staff.Any())
    {
        <partial name="_StaffList" for="Staff" />
    }
    else
    { <p>No Staff Booked </p>}
    @if (Model.Staff.Count() / Model.Guests.Count() < 1)
    {
        <p>Not Enough Staff</p>
    }
</div>


<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ThAmCo.Events/Views/Events/Edit.cshtml
@model ThAmCo.Events.Data.Event

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control"  />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" disabled/>
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeId" class="control-label"></label>
                <input asp-for="TypeId" class="form-control" disabled />  
                <span asp-validation-for="TypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ThAmCo.Events/Views/Events/Index.cshtml
@model IEnumerable<ThAmCo.Events.Data.Event>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TypeId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TypeId)
            </td>
            <td>
                <a asp-action="Index" asp-controller="GuestBookings" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Bookings.Count)</a>
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
                <a asp-area="" asp-controller="GuestBookings" asp-route-eventId="@item.Id" asp-action="Create">Book Guest</a> |
                <a asp-area="" asp-controller="StaffBookings" asp-route-eventId="@item.Id" asp-action="Create">Book Staff</a> |
                <a asp-area="" asp-controller="GuestBookings" asp-route-id="@item.Id" asp-action="Index">Delete Guest</a> |
                <a asp-area="" asp-controller="StaffBookings" asp-route-id="@item.Id" asp-action="Index">Delete Staff</a> |
            </td>
        </tr>
}
    </tbody>
</table>

ThAmCo.Events/Views/Events/_CustomerList.cshtml
@model IEnumerable<ThAmCo.Events.Data.CustomerEventViewModel>


<table class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Surname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>

                <td>
                    @Html.ActionLink("Details", "Details", "Customers", new { id = item.CustomerId })
                    <a asp-area="" asp-controller="GuestBooking" asp-route-eventId="@item.CustomerId,item.EventID" asp-action="Delete">Delete Guest</a> |
                </td>
            </tr>
        }
    </tbody>
</table>

ThAmCo.Events/Views/Events/_StaffList.cshtml
@model IEnumerable<ThAmCo.Events.Data.StaffEventViewModel>


<table class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Surname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>

                <td>
                    @Html.ActionLink("Details", "Details", "Staff", new { id = item.StaffId })
                    <a asp-area="" asp-controller="StaffBookings" asp-route-eventId="@item.StaffId,item.EventID" asp-action="Create">Book Staff</a> |
                </td>
            </tr>
        }
    </tbody>
</table>